### ISSUE TITLE
Badly sampled randomness mod Q ?

### ISSUE THREAD

**Issue by obronchain** [fragerar/HOTableConv#1]
In polycomp.c, some randomness that should be uniform modulo Q is not. As an example in:

https://github.com/fragerar/HOTableConv/blob/0bfc64cf95b7350b8788150a0ff482bea44f508b/Masked_KEMs/Kyber/polycomp.c#L255

I guess that one should use rand_q(r) similarly as for sec_mut(). This will also avoid to waste randomness.

**Comment by fragerar** [comment]
This should be fixed now (commit 8fe91cb).
